{application,simple_cache,
             [{description,"Simple caching system, OTP-style."},
              {vsn,"0.1.0"},
              {modules,[custom_error_report,die_please,sc_app,sc_element,
                        sc_element_sup,sc_event,sc_event_logger,sc_store,
                        sc_sup,simple_cache]},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{sc_app,[]}},
              {env,[]}]}.
